### ISSUE TITLE
package on npmjs

### ISSUE THREAD

**Issue by olivbau** [debridge-finance/solana-tx-parser-public#1]
Nice project!
I dont find the `@debridge-finance/solana-transaction-parser` npm package:
Do you plan to publish it on npm ?

**Comment by devDesu** [comment]
Hello! We're planning to publish the package soon. But before publication I want to verify that all transactions are being parsed correclty, so any feedback is appreciated. 
You can install this package without npm using following command `npm i git+https://github.com/debridge-finance/solana-tx-parser-public`

**Comment by devDesu** [comment]
Added installation hint into the readme
