### ISSUE TITLE
Getting an unhandled error "TypeError: Cannot read properties of null (reading 'property')" on specific transaction

### ISSUE THREAD

**Issue by mordonez-me** [debridge-finance/solana-tx-parser-public#8]
Hi, I am getting a specific error with the following transaction:

["4Xfz6Yb5QK2H6z7Q1R4S5pQQ5QW8V14djncR2LcMW6G7BbDo8xtnA4LzbWKPsB7QS2BEd8GPduqB41FvrnRPugFY"](https://solscan.io/tx/4Xfz6Yb5QK2H6z7Q1R4S5pQQ5QW8V14djncR2LcMW6G7BbDo8xtnA4LzbWKPsB7QS2BEd8GPduqB41FvrnRPugFY)

It looks like one of the accounts can't be decoded.

![image](https://github.com/debridge-finance/solana-tx-parser-public/assets/2242042/f3389b2e-fca1-41da-bca6-1b4c1f2d8baf)

I am using the method flattenTransactionResponse

**Comment by devDesu** [comment]
Hi! FlattenTxResponse does not parse transaction data, it just converts `compiledInstructions` -> `TransactionInstruction[]`.
Issue might be somewhere else. Could you please share your code?

**Comment by mordonez-me** [comment]
Sure, this is the relevant part of the code, first calling getTransaction (web3.js) then calling flattenTxResponse then calling parseInstruction.

![image](https://github.com/debridge-finance/solana-tx-parser-public/assets/2242042/027b6c38-dd67-40d7-9e15-bdc382f0182c)

I had to add the try/catch because it was failing with the tx I posted

**Comment by devDesu** [comment]
Got it, so it's not `flattenTransactionResponse` but `parseInstruction` fail. 
Maybe you're using an outdated idl to parse txs? Could you please share IDLs you're using?

Btw you could ping me on [deBridge developers discord channel](https://discord.com/channels/875308315700264970/876748142777864202), that'll be faster communication
